name:                statistics-probability
version:             0.1.0.0
github:              "githubuser/statistics-probability"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/statistics-probability#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

# executables:
#   statistics-probability-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - statistics-probability

tests:
  statistics-probability-test:
    main:                ExpressionsSpec.hs
    source-dirs:         test
    ghc-options:
    - -main-is ExpressionsSpec
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statistics-probability
    - hspec
    - QuickCheck
